
package Vista;

import Controlador.*;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.*;
import java.util.GregorianCalendar;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.TableView;

/**
 *
 * @author Matias
 */
public class Menu extends javax.swing.JFrame {        
    static ResultSet res,nom,resNick,resPass,ResYaEntro;
    DAO d = new DAO();
    java.util.Date hora = new Date();
    String entro, p, n, name,Clave,Usuario;
    int tamañoTabla = 0;
    Date tiempo;
    static ResultSet ResNombre,ResRut;
    private String rutBusqueda,resutadoNombre, resultadoTipo; 
    private String sent = "true";
    private int numModulo = 2;
    private  JOptionPane msg;
    private ImprimirTiket tk = new ImprimirTiket();

    public Menu() {     
        Deshabilitar();
        initComponents();  
        Conexion.getConexion();
        cargarRegistros();
        InVisible();
        FullScrean();
        IniciarReloj();
        Normal();
        Inicio();    
    }

    private void Inicio(){        
        JPanelMenuApp.setVisible(false);
//        TxtUsuarioMenu.setText("");
//        TxtPassMenu.setText("");
        TxtUsuarioMenu.requestFocus();}
    
    private void Normal(){
        TxtRutFuncionario.requestFocus();
        TxtRutFuncionario.setText("");
        TxtNombreFuncionario.setText("");
        BtnE.isSelected();
    }
    
    
    private void IniciarReloj(){
        Reloj hilo = new Reloj(LblHora);
        hilo.start();
    }
    
    private void Deshabilitar (){
        this.setUndecorated(true);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
    }

    private void InVisible(){
        BtnCerrar.setOpaque(false);
        BtnCerrar.setContentAreaFilled(false);                  
        BtnCerrar.setBorderPainted(false);
    }
    
    private void FullScrean (){   
        Toolkit tk = Toolkit.getDefaultToolkit();
            int xsize = (int) tk.getScreenSize().getWidth();
            int ysize = (int) tk.getScreenSize().getHeight();         
        this.setSize(xsize,ysize);     
    }
    
    
      public void cargarRegistros(){
        
        DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
        modelo.setRowCount(0);
        res= Conexion.Consulta("select  Nom_Fun, Tipo_Reg   from registro order by Cod_Reg DESC ");
        try {
            while(res.next()){
                Vector v= new Vector();
                v.add(res.getString(1));
                v.add(res.getString(2));
                modelo.addRow(v);
                Tabla.setModel(modelo);
            }
        } catch (Exception e) {
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoEntradaSalida = new javax.swing.ButtonGroup();
        JPanelMenuApp = new javax.swing.JDesktopPane();
        PanelPrincipal = new javax.swing.JPanel();
        PanelFuncionario = new javax.swing.JPanel();
        TxtNombreFuncionario = new javax.swing.JTextField();
        TxtRutFuncionario = new javax.swing.JTextField();
        LblHora = new javax.swing.JLabel();
        BtnE = new javax.swing.JRadioButton();
        BtnS = new javax.swing.JRadioButton();
        TxtTipoFuncionario = new javax.swing.JTextField();
        PanelTecladoNumerico = new javax.swing.JPanel();
        Btn2 = new javax.swing.JButton();
        BtnRegistrar = new javax.swing.JButton();
        Btn1 = new javax.swing.JButton();
        Btn4 = new javax.swing.JButton();
        Btn5 = new javax.swing.JButton();
        Btn3 = new javax.swing.JButton();
        Btn6 = new javax.swing.JButton();
        Btn7 = new javax.swing.JButton();
        Btn8 = new javax.swing.JButton();
        Btn9 = new javax.swing.JButton();
        BtnK = new javax.swing.JButton();
        Btn0 = new javax.swing.JButton();
        BtnBorrar = new javax.swing.JButton();
        PanelRegistros = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        BtnCerrar = new javax.swing.JButton();
        JPanelMenuLogeo = new javax.swing.JDesktopPane();
        PanelLogeo = new javax.swing.JPanel();
        PanelLogeoInterior = new javax.swing.JPanel();
        TxtUsuarioMenu = new javax.swing.JTextField();
        TxtPassMenu = new javax.swing.JPasswordField();
        BtnEntrar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanelMenuApp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        PanelPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 8));
        PanelPrincipal.setPreferredSize(new java.awt.Dimension(600, 500));

        PanelFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Funcionario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 30))); // NOI18N

        TxtNombreFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        TxtNombreFuncionario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtNombreFuncionario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        TxtNombreFuncionario.setRequestFocusEnabled(false);
        TxtNombreFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreFuncionarioActionPerformed(evt);
            }
        });

        TxtRutFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        TxtRutFuncionario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtRutFuncionario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        TxtRutFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtRutFuncionarioKeyPressed(evt);
            }
        });

        LblHora.setFont(new java.awt.Font("Segoe UI", 1, 95)); // NOI18N
        LblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblHora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        GrupoEntradaSalida.add(BtnE);
        BtnE.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        BtnE.setSelected(true);
        BtnE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonEntrada1.png"))); // NOI18N
        BtnE.setPreferredSize(new java.awt.Dimension(200, 50));
        BtnE.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotoneEntrada2.png"))); // NOI18N
        BtnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEActionPerformed(evt);
            }
        });

        GrupoEntradaSalida.add(BtnS);
        BtnS.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        BtnS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonSalida1.png"))); // NOI18N
        BtnS.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BotonSalirda2.png"))); // NOI18N
        BtnS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSActionPerformed(evt);
            }
        });

        TxtTipoFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        TxtTipoFuncionario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtTipoFuncionario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        TxtTipoFuncionario.setRequestFocusEnabled(false);
        TxtTipoFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtTipoFuncionarioKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout PanelFuncionarioLayout = new javax.swing.GroupLayout(PanelFuncionario);
        PanelFuncionario.setLayout(PanelFuncionarioLayout);
        PanelFuncionarioLayout.setHorizontalGroup(
            PanelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtNombreFuncionario)
                    .addGroup(PanelFuncionarioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PanelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnE, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnS, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelFuncionarioLayout.createSequentialGroup()
                        .addComponent(TxtRutFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TxtTipoFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelFuncionarioLayout.setVerticalGroup(
            PanelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelFuncionarioLayout.createSequentialGroup()
                .addComponent(LblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtRutFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtTipoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtNombreFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(BtnE, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(BtnS, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        PanelTecladoNumerico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Teclado Numerico", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 30))); // NOI18N

        Btn2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Btn2.setText("2");
        Btn2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn2ActionPerformed(evt);
            }
        });

        BtnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        BtnRegistrar.setText("REGISTRAR");
        BtnRegistrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });

        Btn1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Btn1.setText("1");
        Btn1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn1ActionPerformed(evt);
            }
        });

        Btn4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Btn4.setText("4");
        Btn4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn4ActionPerformed(evt);
            }
        });

        Btn5.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Btn5.setText("5");
        Btn5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn5ActionPerformed(evt);
            }
        });

        Btn3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Btn3.setText("3");
        Btn3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn3ActionPerformed(evt);
            }
        });

        Btn6.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Btn6.setText("6");
        Btn6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn6ActionPerformed(evt);
            }
        });

        Btn7.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Btn7.setText("7");
        Btn7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn7ActionPerformed(evt);
            }
        });

        Btn8.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Btn8.setText("8");
        Btn8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn8ActionPerformed(evt);
            }
        });

        Btn9.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Btn9.setText("9");
        Btn9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn9ActionPerformed(evt);
            }
        });

        BtnK.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        BtnK.setText("K");
        BtnK.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        BtnK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKActionPerformed(evt);
            }
        });

        Btn0.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        Btn0.setText("0");
        Btn0.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn0ActionPerformed(evt);
            }
        });

        BtnBorrar.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        BtnBorrar.setText("<<");
        BtnBorrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        BtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelTecladoNumericoLayout = new javax.swing.GroupLayout(PanelTecladoNumerico);
        PanelTecladoNumerico.setLayout(PanelTecladoNumericoLayout);
        PanelTecladoNumericoLayout.setHorizontalGroup(
            PanelTecladoNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTecladoNumericoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelTecladoNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                    .addGroup(PanelTecladoNumericoLayout.createSequentialGroup()
                        .addGroup(PanelTecladoNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnK, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(PanelTecladoNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Btn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(Btn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(PanelTecladoNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Btn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btn9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
        );
        PanelTecladoNumericoLayout.setVerticalGroup(
            PanelTecladoNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTecladoNumericoLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(PanelTecladoNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelTecladoNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(PanelTecladoNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(PanelTecladoNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(PanelTecladoNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnK, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(BtnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        PanelRegistros.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registros", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 30))); // NOI18N

        Tabla.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "TIPO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla.setColumnSelectionAllowed(true);
        Tabla.setEnabled(false);
        Tabla.setRowHeight(40);
        Tabla.setRowMargin(2);
        jScrollPane1.setViewportView(Tabla);
        Tabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (Tabla.getColumnModel().getColumnCount() > 0) {
            Tabla.getColumnModel().getColumn(0).setResizable(false);
            Tabla.getColumnModel().getColumn(0).setPreferredWidth(280);
            Tabla.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout PanelRegistrosLayout = new javax.swing.GroupLayout(PanelRegistros);
        PanelRegistros.setLayout(PanelRegistrosLayout);
        PanelRegistrosLayout.setHorizontalGroup(
            PanelRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelRegistrosLayout.setVerticalGroup(
            PanelRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistrosLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 24, Short.MAX_VALUE)
                .addComponent(PanelFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(PanelTecladoNumerico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelTecladoNumerico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        BtnCerrar.setBackground(new java.awt.Color(59, 87, 114));
        BtnCerrar.setDefaultCapable(false);
        BtnCerrar.setOpaque(false);
        BtnCerrar.setPreferredSize(new java.awt.Dimension(100, 50));
        BtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarActionPerformed(evt);
            }
        });

        JPanelMenuApp.setLayer(PanelPrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JPanelMenuApp.setLayer(BtnCerrar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout JPanelMenuAppLayout = new javax.swing.GroupLayout(JPanelMenuApp);
        JPanelMenuApp.setLayout(JPanelMenuAppLayout);
        JPanelMenuAppLayout.setHorizontalGroup(
            JPanelMenuAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelMenuAppLayout.createSequentialGroup()
                .addContainerGap(715, Short.MAX_VALUE)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(716, Short.MAX_VALUE))
            .addGroup(JPanelMenuAppLayout.createSequentialGroup()
                .addComponent(BtnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JPanelMenuAppLayout.setVerticalGroup(
            JPanelMenuAppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelMenuAppLayout.createSequentialGroup()
                .addComponent(BtnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 467, Short.MAX_VALUE)
                .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(472, Short.MAX_VALUE))
        );

        BtnCerrar.getAccessibleContext().setAccessibleName("BtnCerrarApp");
        BtnCerrar.getAccessibleContext().setAccessibleDescription("");

        JPanelMenuLogeo.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        JPanelMenuLogeo.setAlignmentX(0.0F);
        JPanelMenuLogeo.setAlignmentY(0.0F);

        PanelLogeo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 6));
        PanelLogeo.setAlignmentX(0.0F);
        PanelLogeo.setAlignmentY(0.0F);
        PanelLogeo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        PanelLogeoInterior.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Logeo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 30))); // NOI18N

        TxtUsuarioMenu.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        TxtUsuarioMenu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtUsuarioMenu.setText("177470333");
        TxtUsuarioMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        TxtUsuarioMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtUsuarioMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuarioMenuActionPerformed(evt);
            }
        });

        TxtPassMenu.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        TxtPassMenu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtPassMenu.setText("123456");
        TxtPassMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        BtnEntrar.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        BtnEntrar.setText("ENTRAR");
        BtnEntrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        BtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEntrarActionPerformed(evt);
            }
        });

        BtnSalir.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        BtnSalir.setText("SALIR");
        BtnSalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelLogeoInteriorLayout = new javax.swing.GroupLayout(PanelLogeoInterior);
        PanelLogeoInterior.setLayout(PanelLogeoInteriorLayout);
        PanelLogeoInteriorLayout.setHorizontalGroup(
            PanelLogeoInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogeoInteriorLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(PanelLogeoInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtPassMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(TxtUsuarioMenu))
                .addGap(37, 37, 37)
                .addGroup(PanelLogeoInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        PanelLogeoInteriorLayout.setVerticalGroup(
            PanelLogeoInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLogeoInteriorLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(PanelLogeoInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtUsuarioMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelLogeoInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtPassMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelLogeoLayout = new javax.swing.GroupLayout(PanelLogeo);
        PanelLogeo.setLayout(PanelLogeoLayout);
        PanelLogeoLayout.setHorizontalGroup(
            PanelLogeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLogeoLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(PanelLogeoInterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        PanelLogeoLayout.setVerticalGroup(
            PanelLogeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLogeoLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(PanelLogeoInterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        JPanelMenuLogeo.setLayer(PanelLogeo, javax.swing.JLayeredPane.MODAL_LAYER);

        javax.swing.GroupLayout JPanelMenuLogeoLayout = new javax.swing.GroupLayout(JPanelMenuLogeo);
        JPanelMenuLogeo.setLayout(JPanelMenuLogeoLayout);
        JPanelMenuLogeoLayout.setHorizontalGroup(
            JPanelMenuLogeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelMenuLogeoLayout.createSequentialGroup()
                .addContainerGap(1124, Short.MAX_VALUE)
                .addComponent(PanelLogeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1125, Short.MAX_VALUE))
        );
        JPanelMenuLogeoLayout.setVerticalGroup(
            JPanelMenuLogeoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelMenuLogeoLayout.createSequentialGroup()
                .addContainerGap(701, Short.MAX_VALUE)
                .addComponent(PanelLogeo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(701, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelMenuLogeo)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPanelMenuApp))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelMenuLogeo)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JPanelMenuApp))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarActionPerformed
        int seleccion = JOptionPane.showOptionDialog(
        this, // Componente padre
        "¿DESEA SALIR DEL PROGRAMA?", //Mensaje
        "SELECCIONE UNA OPCION", // Título
        JOptionPane.YES_NO_CANCEL_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,    // null para icono por defecto.
        new Object[] { "SI", "NO"},    // null para YES, NO y CANCEL
        "SI");
        //PREGUNTA
            if (seleccion != -1){
                if((seleccion + 1)==1){
                   System.exit(0);
                }else{
          // PRESIONO NO
                }
        }
    }//GEN-LAST:event_BtnCerrarActionPerformed

    private void Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1ActionPerformed
       TxtRutFuncionario.setText(TxtRutFuncionario.getText()+"1");
       TxtRutFuncionario.requestFocus();
    }//GEN-LAST:event_Btn1ActionPerformed

    private void Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2ActionPerformed
        TxtRutFuncionario.setText(TxtRutFuncionario.getText()+"2");
        TxtRutFuncionario.requestFocus();
    }//GEN-LAST:event_Btn2ActionPerformed

    private void Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn3ActionPerformed
        TxtRutFuncionario.setText(TxtRutFuncionario.getText()+"3");
        TxtRutFuncionario.requestFocus();
    }//GEN-LAST:event_Btn3ActionPerformed

    private void Btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn4ActionPerformed
        TxtRutFuncionario.setText(TxtRutFuncionario.getText()+"4");
        TxtRutFuncionario.requestFocus();
    }//GEN-LAST:event_Btn4ActionPerformed

    private void Btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn5ActionPerformed
        TxtRutFuncionario.setText(TxtRutFuncionario.getText()+"5");
        TxtRutFuncionario.requestFocus();
    }//GEN-LAST:event_Btn5ActionPerformed

    private void Btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn6ActionPerformed
        TxtRutFuncionario.setText(TxtRutFuncionario.getText()+"6");
        TxtRutFuncionario.requestFocus();
    }//GEN-LAST:event_Btn6ActionPerformed

    private void Btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn7ActionPerformed
       TxtRutFuncionario.setText(TxtRutFuncionario.getText()+"7");
       TxtRutFuncionario.requestFocus();
    }//GEN-LAST:event_Btn7ActionPerformed

    private void Btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn8ActionPerformed
        TxtRutFuncionario.setText(TxtRutFuncionario.getText()+"8");
        TxtRutFuncionario.requestFocus();
    }//GEN-LAST:event_Btn8ActionPerformed

    private void Btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn9ActionPerformed
        TxtRutFuncionario.setText(TxtRutFuncionario.getText()+"9");
        TxtRutFuncionario.requestFocus();
    }//GEN-LAST:event_Btn9ActionPerformed

    private void BtnKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKActionPerformed
        TxtRutFuncionario.setText(TxtRutFuncionario.getText()+"k");
        TxtRutFuncionario.requestFocus();
    }//GEN-LAST:event_BtnKActionPerformed

    private void Btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn0ActionPerformed
        TxtRutFuncionario.setText(TxtRutFuncionario.getText()+"0");
        TxtRutFuncionario.requestFocus();
    }//GEN-LAST:event_Btn0ActionPerformed

    private void BtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBorrarActionPerformed
        String Cadena;
        Cadena= TxtRutFuncionario.getText();
                
        if(Cadena.length()>0){
            
            Cadena = Cadena.substring(0, Cadena.length() - 1);
            TxtRutFuncionario.setText(Cadena);
        }
        TxtRutFuncionario.requestFocus();
    }//GEN-LAST:event_BtnBorrarActionPerformed

    

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        int seleccion = JOptionPane.showOptionDialog(
            this, // Componente padre
              "¿DESEA SALIR DEL PROGRAMA?", //Mensaje
        "SELECCIONE UNA OPCION", // Título
            JOptionPane.YES_NO_CANCEL_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,    // null para icono por defecto.
            new Object[] { "SI", "NO"},    // null para YES, NO y CANCEL
            "SI");
        //PREGUNTA
        if (seleccion != -1){
            if((seleccion + 1)==1){
                System.exit(0);
            }else{
                // PRESIONO NO
            }
        }
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEntrarActionPerformed
          String usuario = TxtUsuarioMenu.getText();
        String clave = TxtPassMenu.getText();
        
        Usuario = d.getUser(clave);
        Clave   = d.getPass(usuario);

        System.out.println(Clave);
        System.out.println(Usuario);
        
         if(TxtUsuarioMenu.getText().equals(Usuario) && TxtPassMenu.getText().equals(Clave)){             
            JPanelMenuApp.setVisible(true);
            JPanelMenuLogeo.setVisible(false);
            PanelLogeo.setVisible(false);
            TxtRutFuncionario.requestFocus();
        }else{
            JOptionPane.showMessageDialog(this, "INGRESE USUARIO Y CLAVE CORRECTA","ERROR DE AUTENTIFICACION",1,null);
            TxtUsuarioMenu.setText("");
            TxtPassMenu.setText("");
            TxtUsuarioMenu.requestFocus();
        }
    }//GEN-LAST:event_BtnEntrarActionPerformed
    
    public void JopMensaje(String mensaje, int tipo, String titulo ){
        msg =  new  JOptionPane (  ""+mensaje+"",  tipo); 
        final  JDialog dlg = msg . createDialog (this, ""+titulo+"" ); 
        dlg . setDefaultCloseOperation ( JDialog . DO_NOTHING_ON_CLOSE ); 
        new  Thread ( new  Runnable ()  { 
          @Override 
          public  void run ()  { 
            try  { 
              Thread . sleep ( 3000 ); 
            }  catch  ( InterruptedException e )  { 
              e . printStackTrace (); 
            } 
            dlg . setVisible ( false ); 
          } 
        }). start (); 
        dlg . setVisible ( true );
    }
    
    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        rutBusqueda = TxtRutFuncionario.getText();
        resutadoNombre = d.getFuncionario(rutBusqueda);
        resultadoTipo = d.getTipoDeEntrada(rutBusqueda);
        tamañoTabla = d.getHayRegistros(rutBusqueda);
              
        if(!TxtRutFuncionario.getText().trim().equals("")){
            if(!(resutadoNombre == null)){ 
                TxtNombreFuncionario.setText(resutadoNombre);
                if(tamañoTabla == 0){
                    if(BtnE.isSelected()){
                        try {
                            d.RegistrarRegistros(rutBusqueda, resutadoNombre, numModulo, "ENTRADA");
                            TxtTipoFuncionario.setText("ENTRADA");
                            tk.printTexto("Instituto Ingles", resutadoNombre, d.getFechaActual(), LblHora.getText(), "INPUT");             
                            JopMensaje("ENTRADA REGISTRADA",1,"REGISTRADO"); 
                           
                            cargarRegistros();
                        } catch (SQLException ex) {
                            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }else{
                        JopMensaje("SU PRIMER REGISTRO DEBE SER ENTRADA",0,"ERROR");
                    }
                }else   
                if(BtnE.isSelected()){
                    if(!resultadoTipo.equals("SALIDA")){     
                        JopMensaje("SU ULTIMO REGISTRO FUE ENTRADA, FAVOR DE MARCAR SALIDA",0,"ERROR");
                    }
                    if(resultadoTipo.equals("SALIDA")){
                        TxtTipoFuncionario.setText("ENTRADA");
                        try {
                            if(d.EstadoDelay(rutBusqueda).equals("TRUE")){
                                try {
                                    d.RegistrarRegistros(rutBusqueda, resutadoNombre, numModulo, "ENTRADA");
                                    tk.printTexto("Instituto Ingles", resutadoNombre, d.getFechaActual(), LblHora.getText(), "INPUT");
                                    JopMensaje("ENTRADA REGISTRADA",1,"REGISTRADO"); 
                                   
                                } catch (SQLException ex) {
                                    Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                                }
                                cargarRegistros();
                            }else{  
                                JopMensaje("ESPERE UNOS SEGUNDOS PARA VOLVER A REGISTRAR",2,"ERROR");
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }else
                    if(BtnS.isSelected()){
                        if(!resultadoTipo.equals("ENTRADA")){ 
                            JopMensaje("SU ULTIMO REGISTRO FUE SALIDA, FAVOR DE MARCAR ENTRADA",0,"ERROR");
                        }
                        if(resultadoTipo.equals("ENTRADA")){
                            TxtTipoFuncionario.setText("SALIDA");
                            try {
                                if(d.EstadoDelay(rutBusqueda).equals("TRUE")){
                                    try {                                       
                                        d.RegistrarRegistros(rutBusqueda, resutadoNombre, numModulo, "SALIDA");
                                        tk.printTexto("Instituto Ingles", resutadoNombre, d.getFechaActual(),LblHora.getText() , "OUTPUT");
                                        JopMensaje("SALIDA REGISTRADA",1,"REGISTRADO"); 
                                    } catch (SQLException ex) {
                                        Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                    cargarRegistros();             
                                }else{                          
                                    JopMensaje("ESPERE UNOS SEGUNDOS PARA VOLVER A REGISTRAR",2,"ERROR");
                                }
                            } catch (SQLException ex) {
                                Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    }
            }else{             
                JopMensaje("USUARIO NO REGISTRADO",0,"ERROR");
            }   
        }else{       
            JopMensaje("INGRESE DATOS",0,"ERROR");
        }
        TxtRutFuncionario.setText("");
        TxtNombreFuncionario.setText("");
        TxtRutFuncionario.requestFocus();
        TxtTipoFuncionario.setText("");
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void TxtNombreFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreFuncionarioActionPerformed

    private void TxtUsuarioMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuarioMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuarioMenuActionPerformed

    private void BtnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEActionPerformed
        TxtRutFuncionario.requestFocus();
    }//GEN-LAST:event_BtnEActionPerformed

    private void TxtRutFuncionarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRutFuncionarioKeyPressed
    
    int key=evt.getKeyCode();
        if(key==KeyEvent.VK_ENTER)
        {     
            BtnRegistrar.doClick();                             
        }
    }//GEN-LAST:event_TxtRutFuncionarioKeyPressed

    private void BtnSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSActionPerformed
         TxtRutFuncionario.requestFocus();
    }//GEN-LAST:event_BtnSActionPerformed

    private void TxtTipoFuncionarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTipoFuncionarioKeyPressed
        
    }//GEN-LAST:event_TxtTipoFuncionarioKeyPressed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn0;
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JButton Btn4;
    private javax.swing.JButton Btn5;
    private javax.swing.JButton Btn6;
    private javax.swing.JButton Btn7;
    private javax.swing.JButton Btn8;
    private javax.swing.JButton Btn9;
    private javax.swing.JButton BtnBorrar;
    private javax.swing.JButton BtnCerrar;
    private javax.swing.JRadioButton BtnE;
    private javax.swing.JButton BtnEntrar;
    private javax.swing.JButton BtnK;
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JRadioButton BtnS;
    private javax.swing.JButton BtnSalir;
    private javax.swing.ButtonGroup GrupoEntradaSalida;
    private javax.swing.JDesktopPane JPanelMenuApp;
    private javax.swing.JDesktopPane JPanelMenuLogeo;
    private javax.swing.JLabel LblHora;
    private javax.swing.JPanel PanelFuncionario;
    private javax.swing.JPanel PanelLogeo;
    private javax.swing.JPanel PanelLogeoInterior;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PanelRegistros;
    private javax.swing.JPanel PanelTecladoNumerico;
    private javax.swing.JTable Tabla;
    private javax.swing.JTextField TxtNombreFuncionario;
    private javax.swing.JPasswordField TxtPassMenu;
    private javax.swing.JTextField TxtRutFuncionario;
    private javax.swing.JTextField TxtTipoFuncionario;
    private javax.swing.JTextField TxtUsuarioMenu;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
